name: Release Announce

on:
  push:
    branches:
      - master

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - uses: satoryu/typetalk-notify
        with:
          token: ${{ secrets.TYPETALK_TOKEN }}
          topic_id: 165952
          message: "${{ github.repository }} ${{ github.ref }} has been released :tada: :white_flower:"
