name: Update master branch

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: satoryu/typetalk-notify@master
        with:
          token: ${{ secrets.TYPETALK_TOKEN }}
          topic_id: ${{ secrets.TYPETALK_TOPIC_ID }}
          message: "${{ github.repository }} ${{ github.ref }} has been updated :new:
